/*
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
 * Autogenerated by Loqui.  Do not manually change.
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 
*/
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Loqui;
using Noggog;
using Noggog.Notifying;
using MusicRecord.Internals;
using System.Xml;
using System.Xml.Linq;
using System.IO;
using Noggog.Xml;
using Loqui.Xml;
using Loqui.Internal;
using System.Diagnostics;
using System.Collections.Specialized;

namespace MusicRecord
{
    #region Class
    public partial class Artist : 
        IArtist,
        ILoquiObject<Artist>,
        ILoquiObjectSetter,
        IEquatable<Artist>
    {
        [DebuggerBrowsable(DebuggerBrowsableState.Never)]
        ILoquiRegistration ILoquiObject.Registration => Artist_Registration.Instance;
        public static Artist_Registration Registration => Artist_Registration.Instance;

        #region Ctor
        public Artist()
        {
            _hasBeenSetTracker = new BitArray(((ILoquiObject)this).Registration.FieldCount);
            CustomCtor();
        }
        partial void CustomCtor();
        #endregion

        #region Name
        public String Name { get; set; }
        protected void UnsetName()
        {
            _hasBeenSetTracker[(int)Artist_FieldIndex.Name] = false;
            Name = default(String);
        }
        #endregion
        #region Albums
        private readonly INotifyingKeyedCollection<String, Album> _Albums = new NotifyingKeyedCollection<String, Album>((item) => item.Name);
        public INotifyingKeyedCollection<String, Album> Albums => _Albums;
        #region Interface Members
        INotifyingKeyedCollection<String, Album> IArtist.Albums => _Albums;
        INotifyingKeyedCollectionGetter<String, Album> IArtistGetter.Albums => _Albums;
        #endregion

        #endregion

        #region Loqui Getter Interface

        protected object GetNthObject(ushort index) => ArtistCommon.GetNthObject(index, this);
        object ILoquiObjectGetter.GetNthObject(ushort index) => this.GetNthObject(index);

        protected bool GetNthObjectHasBeenSet(ushort index) => ArtistCommon.GetNthObjectHasBeenSet(index, this);
        bool ILoquiObjectGetter.GetNthObjectHasBeenSet(ushort index) => this.GetNthObjectHasBeenSet(index);

        protected void UnsetNthObject(ushort index, NotifyingUnsetParameters cmds) => ArtistCommon.UnsetNthObject(index, this, cmds);
        void ILoquiObjectSetter.UnsetNthObject(ushort index, NotifyingUnsetParameters cmds) => this.UnsetNthObject(index, cmds);

        #endregion

        #region Loqui Interface
        protected void SetNthObjectHasBeenSet(ushort index, bool on)
        {
            ArtistCommon.SetNthObjectHasBeenSet(index, on, this);
        }
        void ILoquiObjectSetter.SetNthObjectHasBeenSet(ushort index, bool on) => this.SetNthObjectHasBeenSet(index, on);

        #endregion

        IMask<bool> IEqualsMask<Artist>.GetEqualsMask(Artist rhs) => ArtistCommon.GetEqualsMask(this, rhs);
        IMask<bool> IEqualsMask<IArtistGetter>.GetEqualsMask(IArtistGetter rhs) => ArtistCommon.GetEqualsMask(this, rhs);
        #region To String
        public override string ToString()
        {
            return ArtistCommon.ToString(this, printMask: null);
        }

        public string ToString(
            string name = null,
            Artist_Mask<bool> printMask = null)
        {
            return ArtistCommon.ToString(this, name: name, printMask: printMask);
        }

        public void ToString(
            FileGeneration fg,
            string name = null)
        {
            ArtistCommon.ToString(this, fg, name: name, printMask: null);
        }

        #endregion

        IMask<bool> ILoquiObjectGetter.GetHasBeenSetMask() => this.GetHasBeenSetMask();
        public Artist_Mask<bool> GetHasBeenSetMask()
        {
            return ArtistCommon.GetHasBeenSetMask(this);
        }
        #region Equals and Hash
        public override bool Equals(object obj)
        {
            if (!(obj is Artist rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Artist rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.Name, rhs.Name)) return false;
            if (!this.Albums.SequenceEqual(rhs.Albums)) return false;
            return true;
        }

        public override int GetHashCode()
        {
            int ret = 0;
            ret = HashHelper.GetHashCode(Name).CombineHashCode(ret);
            ret = HashHelper.GetHashCode(Albums).CombineHashCode(ret);
            return ret;
        }

        #endregion


        #region Xml Translation
        #region Xml Create
        [DebuggerStepThrough]
        public static Artist Create_Xml(
            XElement root,
            Artist_TranslationMask translationMask = null)
        {
            return Create_Xml(
                root: root,
                errorMask: null,
                translationMask: translationMask?.GetCrystal());
        }

        [DebuggerStepThrough]
        public static Artist Create_Xml(
            XElement root,
            out Artist_ErrorMask errorMask,
            bool doMasks = true,
            Artist_TranslationMask translationMask = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            var ret = Create_Xml(
                root: root,
                errorMask: errorMaskBuilder,
                translationMask: translationMask.GetCrystal());
            errorMask = Artist_ErrorMask.Factory(errorMaskBuilder);
            return ret;
        }

        public static Artist Create_Xml(
            XElement root,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            var ret = new Artist();
            try
            {
                foreach (var elem in root.Elements())
                {
                    Fill_Xml_Internal(
                        item: ret,
                        root: elem,
                        name: elem.Name.LocalName,
                        errorMask: errorMask,
                        translationMask: translationMask);
                }
            }
            catch (Exception ex)
            when (errorMask != null)
            {
                errorMask.ReportException(ex);
            }
            return ret;
        }

        public static Artist Create_Xml(
            string path,
            Artist_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(path).Root;
            return Create_Xml(
                root: root,
                translationMask: translationMask);
        }

        public static Artist Create_Xml(
            string path,
            out Artist_ErrorMask errorMask,
            Artist_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(path).Root;
            return Create_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        public static Artist Create_Xml(
            Stream stream,
            Artist_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(stream).Root;
            return Create_Xml(
                root: root,
                translationMask: translationMask);
        }

        public static Artist Create_Xml(
            Stream stream,
            out Artist_ErrorMask errorMask,
            Artist_TranslationMask translationMask = null)
        {
            var root = XDocument.Load(stream).Root;
            return Create_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask);
        }

        #endregion

        #region Xml Copy In
        public void CopyIn_Xml(
            XElement root,
            NotifyingFireParameters cmds = null)
        {
            CopyIn_Xml_Internal(
                root: root,
                errorMask: null,
                translationMask: null,
                cmds: cmds);
        }

        public virtual void CopyIn_Xml(
            XElement root,
            out Artist_ErrorMask errorMask,
            Artist_TranslationMask translationMask = null,
            bool doMasks = true,
            NotifyingFireParameters cmds = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            CopyIn_Xml_Internal(
                root: root,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal(),
                cmds: cmds);
            errorMask = Artist_ErrorMask.Factory(errorMaskBuilder);
        }

        protected void CopyIn_Xml_Internal(
            XElement root,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            NotifyingFireParameters cmds = null)
        {
            LoquiXmlTranslation<Artist>.Instance.CopyIn(
                root: root,
                item: this,
                skipProtected: true,
                errorMask: errorMask,
                translationMask: translationMask,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            string path,
            NotifyingFireParameters cmds = null)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_Xml(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            string path,
            out Artist_ErrorMask errorMask,
            Artist_TranslationMask translationMask,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var root = XDocument.Load(path).Root;
            this.CopyIn_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask,
                cmds: cmds,
                doMasks: doMasks);
        }

        public void CopyIn_Xml(
            Stream stream,
            NotifyingFireParameters cmds = null)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                root: root,
                cmds: cmds);
        }

        public void CopyIn_Xml(
            Stream stream,
            out Artist_ErrorMask errorMask,
            Artist_TranslationMask translationMask,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var root = XDocument.Load(stream).Root;
            this.CopyIn_Xml(
                root: root,
                errorMask: out errorMask,
                translationMask: translationMask,
                cmds: cmds,
                doMasks: doMasks);
        }

        #endregion

        #region Xml Write
        public virtual void Write_Xml(
            XElement node,
            out Artist_ErrorMask errorMask,
            bool doMasks = true,
            Artist_TranslationMask translationMask = null,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            this.Write_Xml_Internal(
                node: node,
                name: name,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Artist_ErrorMask.Factory(errorMaskBuilder);
        }

        public virtual void Write_Xml(
            string path,
            out Artist_ErrorMask errorMask,
            Artist_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml(
                node: topNode,
                name: name,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            using (var fs = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None, 4096, FileOptions.None))
            {
                topNode.Elements().First().Save(fs);
            }
        }

        public virtual void Write_Xml(
            Stream stream,
            out Artist_ErrorMask errorMask,
            Artist_TranslationMask translationMask = null,
            bool doMasks = true,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml(
                node: topNode,
                name: name,
                errorMask: out errorMask,
                doMasks: doMasks,
                translationMask: translationMask);
            topNode.Elements().First().Save(stream);
        }

        public void Write_Xml(
            XElement node,
            string name = null,
            Artist_TranslationMask translationMask = null)
        {
            this.Write_Xml_Internal(
                node: node,
                name: name,
                errorMask: null,
                translationMask: translationMask.GetCrystal());
        }

        public void Write_Xml(
            string path,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml_Internal(
                node: topNode,
                name: name,
                errorMask: null,
                translationMask: null);
            using (var fs = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.None, 4096, FileOptions.None))
            {
                topNode.Elements().First().Save(fs);
            }
        }

        public void Write_Xml(
            Stream stream,
            string name = null)
        {
            XElement topNode = new XElement("topnode");
            Write_Xml_Internal(
                node: topNode,
                name: name,
                errorMask: null,
                translationMask: null);
            topNode.Elements().First().Save(stream);
        }

        protected void Write_Xml_Internal(
            XElement node,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            ArtistCommon.Write_Xml(
                item: this,
                node: node,
                name: name,
                errorMask: errorMask,
                translationMask: translationMask);
        }
        #endregion

        protected static void Fill_Xml_Internal(
            Artist item,
            XElement root,
            string name,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask)
        {
            switch (name)
            {
                case "Name":
                    try
                    {
                        errorMask?.PushIndex((int)Artist_FieldIndex.Name);
                        if (StringXmlTranslation.Instance.Parse(
                            root: root,
                            item: out String NameParse,
                            errorMask: errorMask))
                        {
                            item.Name = NameParse;
                        }
                        else
                        {
                            item.Name = default(String);
                        }
                    }
                    catch (Exception ex)
                    when (errorMask != null)
                    {
                        errorMask.ReportException(ex);
                    }
                    finally
                    {
                        errorMask?.PopIndex();
                    }
                    break;
                case "Albums":
                    KeyedDictXmlTranslation<String, Album>.Instance.ParseInto(
                        root: root,
                        item: item.Albums,
                        fieldIndex: (int)Artist_FieldIndex.Albums,
                        errorMask: errorMask,
                        translationMask: translationMask,
                        valTransl: LoquiXmlTranslation<Album>.Instance.Parse);
                    break;
                default:
                    break;
            }
        }

        #endregion

        protected readonly BitArray _hasBeenSetTracker;
        protected bool GetHasBeenSet(int index)
        {
            switch ((Artist_FieldIndex)index)
            {
                case Artist_FieldIndex.Name:
                case Artist_FieldIndex.Albums:
                    return true;
                default:
                    throw new ArgumentException($"Unknown field index: {index}");
            }
        }

        public Artist Copy(
            Artist_CopyMask copyMask = null,
            IArtistGetter def = null)
        {
            return Artist.Copy(
                this,
                copyMask: copyMask,
                def: def);
        }

        public static Artist Copy(
            IArtist item,
            Artist_CopyMask copyMask = null,
            IArtistGetter def = null)
        {
            Artist ret;
            if (item.GetType().Equals(typeof(Artist)))
            {
                ret = new Artist();
            }
            else
            {
                ret = (Artist)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public static Artist Copy_ToLoqui(
            IArtistGetter item,
            Artist_CopyMask copyMask = null,
            IArtistGetter def = null)
        {
            Artist ret;
            if (item.GetType().Equals(typeof(Artist)))
            {
                ret = new Artist() as Artist;
            }
            else
            {
                ret = (Artist)System.Activator.CreateInstance(item.GetType());
            }
            ret.CopyFieldsFrom(
                item,
                copyMask: copyMask,
                def: def);
            return ret;
        }

        public void CopyFieldsFrom(
            IArtistGetter rhs,
            NotifyingFireParameters cmds = null)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: null,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: null,
                cmds: cmds);
        }

        public void CopyFieldsFrom(
            IArtistGetter rhs,
            Artist_CopyMask copyMask,
            IArtistGetter def = null,
            NotifyingFireParameters cmds = null)
        {
            this.CopyFieldsFrom(
                rhs: rhs,
                def: def,
                doMasks: false,
                errorMask: out var errMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        public void CopyFieldsFrom(
            IArtistGetter rhs,
            out Artist_ErrorMask errorMask,
            Artist_CopyMask copyMask = null,
            IArtistGetter def = null,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            var errorMaskBuilder = new ErrorMaskBuilder();
            ArtistCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMaskBuilder,
                copyMask: copyMask,
                cmds: cmds);
            errorMask = Artist_ErrorMask.Factory(errorMaskBuilder);
        }

        public void CopyFieldsFrom(
            IArtistGetter rhs,
            ErrorMaskBuilder errorMask,
            Artist_CopyMask copyMask = null,
            IArtistGetter def = null,
            NotifyingFireParameters cmds = null,
            bool doMasks = true)
        {
            ArtistCommon.CopyFieldsFrom(
                item: this,
                rhs: rhs,
                def: def,
                errorMask: errorMask,
                copyMask: copyMask,
                cmds: cmds);
        }

        void ILoquiObjectSetter.SetNthObject(ushort index, object obj, NotifyingFireParameters cmds) => this.SetNthObject(index, obj, cmds);
        protected void SetNthObject(ushort index, object obj, NotifyingFireParameters cmds = null)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    this.Name = (String)obj;
                    break;
                case Artist_FieldIndex.Albums:
                    this.Albums.SetTo(
                        ((IEnumerable<Album>)(NotifyingDictionary<String, Album>)obj),
                        cmds);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        partial void ClearPartial(NotifyingUnsetParameters cmds);

        protected void CallClearPartial_Internal(NotifyingUnsetParameters cmds)
        {
            ClearPartial(cmds);
        }

        public void Clear(NotifyingUnsetParameters cmds = null)
        {
            CallClearPartial_Internal(cmds);
            ArtistCommon.Clear(this, cmds);
        }


        public static Artist Create(IEnumerable<KeyValuePair<ushort, object>> fields)
        {
            var ret = new Artist();
            foreach (var pair in fields)
            {
                CopyInInternal_Artist(ret, pair);
            }
            return ret;
        }

        protected static void CopyInInternal_Artist(Artist obj, KeyValuePair<ushort, object> pair)
        {
            if (!EnumExt.TryParse(pair.Key, out Artist_FieldIndex enu))
            {
                throw new ArgumentException($"Unknown index: {pair.Key}");
            }
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    obj.Name = (String)pair.Value;
                    break;
                case Artist_FieldIndex.Albums:
                    obj.Albums.SetTo(
                        ((IEnumerable<Album>)(NotifyingDictionary<String, Album>)pair.Value),
                        null);
                    break;
                default:
                    throw new ArgumentException($"Unknown enum type: {enu}");
            }
        }
        public static void CopyIn(IEnumerable<KeyValuePair<ushort, object>> fields, Artist obj)
        {
            ILoquiObjectExt.CopyFieldsIn(obj, fields, def: null, skipProtected: false, cmds: null);
        }

    }
    #endregion

    #region Interface
    public partial interface IArtist : IArtistGetter, ILoquiClass<IArtist, IArtistGetter>, ILoquiClass<Artist, IArtistGetter>
    {
        new String Name { get; set; }

        new INotifyingKeyedCollection<String, Album> Albums { get; }
    }

    public partial interface IArtistGetter : ILoquiObject
    {
        #region Name
        String Name { get; }

        #endregion
        #region Albums
        INotifyingKeyedCollectionGetter<String, Album> Albums { get; }
        #endregion

    }

    #endregion

}

namespace MusicRecord.Internals
{
    #region Field Index
    public enum Artist_FieldIndex
    {
        Name = 0,
        Albums = 1,
    }
    #endregion

    #region Registration
    public class Artist_Registration : ILoquiRegistration
    {
        public static readonly Artist_Registration Instance = new Artist_Registration();

        public static ProtocolKey ProtocolKey => ProtocolDefinition_MusicRecord.ProtocolKey;

        public static readonly ObjectKey ObjectKey = new ObjectKey(
            protocolKey: ProtocolDefinition_MusicRecord.ProtocolKey,
            msgID: 3,
            version: 0);

        public const string GUID = "a30710e1-7d54-4d56-bed9-e03907c783bb";

        public const ushort AdditionalFieldCount = 2;

        public const ushort FieldCount = 2;

        public static readonly Type MaskType = typeof(Artist_Mask<>);

        public static readonly Type ErrorMaskType = typeof(Artist_ErrorMask);

        public static readonly Type ClassType = typeof(Artist);

        public static readonly Type GetterType = typeof(IArtistGetter);

        public static readonly Type SetterType = typeof(IArtist);

        public static readonly Type CommonType = typeof(ArtistCommon);

        public const string FullName = "MusicRecord.Artist";

        public const string Name = "Artist";

        public const string Namespace = "MusicRecord";

        public const byte GenericCount = 0;

        public static readonly Type GenericRegistrationType = null;

        public static ushort? GetNameIndex(StringCaseAgnostic str)
        {
            switch (str.Upper)
            {
                case "NAME":
                    return (ushort)Artist_FieldIndex.Name;
                case "ALBUMS":
                    return (ushort)Artist_FieldIndex.Albums;
                default:
                    return null;
            }
        }

        public static bool GetNthIsEnumerable(ushort index)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                case Artist_FieldIndex.Albums:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsLoqui(ushort index)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                case Artist_FieldIndex.Albums:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthIsSingleton(ushort index)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                case Artist_FieldIndex.Albums:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static string GetNthName(ushort index)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    return "Name";
                case Artist_FieldIndex.Albums:
                    return "Albums";
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsNthDerivative(ushort index)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                case Artist_FieldIndex.Albums:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool IsProtected(ushort index)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                case Artist_FieldIndex.Albums:
                    return false;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static Type GetNthType(ushort index)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    return typeof(String);
                case Artist_FieldIndex.Albums:
                    return typeof(NotifyingDictionary<String, Album>);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        #region Interface
        ProtocolKey ILoquiRegistration.ProtocolKey => ProtocolKey;
        ObjectKey ILoquiRegistration.ObjectKey => ObjectKey;
        string ILoquiRegistration.GUID => GUID;
        ushort ILoquiRegistration.FieldCount => FieldCount;
        ushort ILoquiRegistration.AdditionalFieldCount => AdditionalFieldCount;
        Type ILoquiRegistration.MaskType => MaskType;
        Type ILoquiRegistration.ErrorMaskType => ErrorMaskType;
        Type ILoquiRegistration.ClassType => ClassType;
        Type ILoquiRegistration.SetterType => SetterType;
        Type ILoquiRegistration.GetterType => GetterType;
        Type ILoquiRegistration.CommonType => CommonType;
        string ILoquiRegistration.FullName => FullName;
        string ILoquiRegistration.Name => Name;
        string ILoquiRegistration.Namespace => Namespace;
        byte ILoquiRegistration.GenericCount => GenericCount;
        Type ILoquiRegistration.GenericRegistrationType => GenericRegistrationType;
        ushort? ILoquiRegistration.GetNameIndex(StringCaseAgnostic name) => GetNameIndex(name);
        bool ILoquiRegistration.GetNthIsEnumerable(ushort index) => GetNthIsEnumerable(index);
        bool ILoquiRegistration.GetNthIsLoqui(ushort index) => GetNthIsLoqui(index);
        bool ILoquiRegistration.GetNthIsSingleton(ushort index) => GetNthIsSingleton(index);
        string ILoquiRegistration.GetNthName(ushort index) => GetNthName(index);
        bool ILoquiRegistration.IsNthDerivative(ushort index) => IsNthDerivative(index);
        bool ILoquiRegistration.IsProtected(ushort index) => IsProtected(index);
        Type ILoquiRegistration.GetNthType(ushort index) => GetNthType(index);
        #endregion

    }
    #endregion

    #region Extensions
    public static partial class ArtistCommon
    {
        #region Copy Fields From
        public static void CopyFieldsFrom(
            IArtist item,
            IArtistGetter rhs,
            IArtistGetter def,
            ErrorMaskBuilder errorMask,
            Artist_CopyMask copyMask,
            NotifyingFireParameters cmds = null)
        {
            if (copyMask?.Name ?? true)
            {
                errorMask?.PushIndex((int)Artist_FieldIndex.Name);
                item.Name = rhs.Name;
                errorMask?.PopIndex();
            }
            if (copyMask?.Albums.Overall != CopyOption.Skip)
            {
                errorMask?.PushIndex((int)Artist_FieldIndex.Albums);
                try
                {
                    item.Albums.SetToWithDefault(
                        rhs.Albums,
                        def?.Albums,
                        cmds,
                        (r, d) =>
                        {
                            switch (copyMask?.Albums.Overall ?? CopyOption.Reference)
                            {
                                case CopyOption.Reference:
                                    return r;
                                case CopyOption.MakeCopy:
                                    return Album.Copy(
                                        r,
                                        copyMask?.Albums?.Specific,
                                        def: d);
                                default:
                                    throw new NotImplementedException($"Unknown CopyOption {copyMask?.Albums.Overall}. Cannot execute copy.");
                            }
                        }
                        );
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }

        #endregion

        public static void SetNthObjectHasBeenSet(
            ushort index,
            bool on,
            IArtist obj,
            NotifyingFireParameters cmds = null)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                case Artist_FieldIndex.Albums:
                    if (on) break;
                    throw new ArgumentException("Tried to unset a field which does not have this functionality." + index);
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void UnsetNthObject(
            ushort index,
            IArtist obj,
            NotifyingUnsetParameters cmds = null)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    obj.Name = default(String);
                    break;
                case Artist_FieldIndex.Albums:
                    obj.Albums.Unset(cmds);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static bool GetNthObjectHasBeenSet(
            ushort index,
            IArtist obj)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                case Artist_FieldIndex.Albums:
                    return true;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static object GetNthObject(
            ushort index,
            IArtistGetter obj)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    return obj.Name;
                case Artist_FieldIndex.Albums:
                    return obj.Albums;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public static void Clear(
            IArtist item,
            NotifyingUnsetParameters cmds = null)
        {
            item.Name = default(String);
            item.Albums.Unset(cmds.ToUnsetParams());
        }

        public static Artist_Mask<bool> GetEqualsMask(
            this IArtistGetter item,
            IArtistGetter rhs)
        {
            var ret = new Artist_Mask<bool>();
            FillEqualsMask(item, rhs, ret);
            return ret;
        }

        public static void FillEqualsMask(
            IArtistGetter item,
            IArtistGetter rhs,
            Artist_Mask<bool> ret)
        {
            if (rhs == null) return;
            ret.Name = object.Equals(item.Name, rhs.Name);
            ret.Albums = new MaskItem<bool, IEnumerable<MaskItem<bool, Album_Mask<bool>>>>();
            ret.Albums.Specific = item.Albums.Values.SelectAgainst<Album, MaskItem<bool, Album_Mask<bool>>>(rhs.Albums.Values, ((l, r) =>
            {
                MaskItem<bool, Album_Mask<bool>> itemRet;
                itemRet = new MaskItem<bool, Album_Mask<bool>>();
                itemRet.Specific = AlbumCommon.GetEqualsMask(l, r);
                itemRet.Overall = itemRet.Specific.AllEqual((b) => b);
                return itemRet;
            }
            ), out ret.Albums.Overall);
            ret.Albums.Overall = ret.Albums.Overall && ret.Albums.Specific.All((b) => b.Overall);
        }

        public static string ToString(
            this IArtistGetter item,
            string name = null,
            Artist_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            item.ToString(fg, name, printMask);
            return fg.ToString();
        }

        public static void ToString(
            this IArtistGetter item,
            FileGeneration fg,
            string name = null,
            Artist_Mask<bool> printMask = null)
        {
            if (name == null)
            {
                fg.AppendLine($"{nameof(Artist)} =>");
            }
            else
            {
                fg.AppendLine($"{name} ({nameof(Artist)}) =>");
            }
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Name ?? true)
                {
                    fg.AppendLine($"Name => {item.Name}");
                }
                if (printMask?.Albums?.Overall ?? true)
                {
                    fg.AppendLine("Albums =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        foreach (var subItem in item.Albums.Values)
                        {
                            fg.AppendLine("[");
                            using (new DepthWrapper(fg))
                            {
                                subItem?.ToString(fg, "Item");
                            }
                            fg.AppendLine("]");
                        }
                    }
                    fg.AppendLine("]");
                }
            }
            fg.AppendLine("]");
        }

        public static bool HasBeenSet(
            this IArtistGetter item,
            Artist_Mask<bool?> checkMask)
        {
            return true;
        }

        public static Artist_Mask<bool> GetHasBeenSetMask(IArtistGetter item)
        {
            var ret = new Artist_Mask<bool>();
            ret.Name = true;
            ret.Albums = new MaskItem<bool, IEnumerable<MaskItem<bool, Album_Mask<bool>>>>(item.Albums.HasBeenSet, item.Albums.Values.Select((i) => new MaskItem<bool, Album_Mask<bool>>(true, i.GetHasBeenSetMask())));
            return ret;
        }

        #region Xml Translation
        #region Xml Write
        public static void Write_Xml(
            XElement node,
            Artist item,
            bool doMasks,
            out Artist_ErrorMask errorMask,
            Artist_TranslationMask translationMask,
            string name = null)
        {
            ErrorMaskBuilder errorMaskBuilder = doMasks ? new ErrorMaskBuilder() : null;
            Write_Xml(
                node: node,
                name: name,
                item: item,
                errorMask: errorMaskBuilder,
                translationMask: translationMask?.GetCrystal());
            errorMask = Artist_ErrorMask.Factory(errorMaskBuilder);
        }

        public static void Write_Xml(
            XElement node,
            Artist item,
            ErrorMaskBuilder errorMask,
            TranslationCrystal translationMask,
            string name = null)
        {
            var elem = new XElement(name ?? "MusicRecord.Artist");
            node.Add(elem);
            if (name != null)
            {
                elem.SetAttributeValue("type", "MusicRecord.Artist");
            }
            if ((translationMask?.GetShouldTranslate((int)Artist_FieldIndex.Name) ?? true))
            {
                StringXmlTranslation.Instance.Write(
                    node: elem,
                    name: nameof(item.Name),
                    item: item.Name,
                    fieldIndex: (int)Artist_FieldIndex.Name,
                    errorMask: errorMask);
            }
            if ((translationMask?.GetShouldTranslate((int)Artist_FieldIndex.Albums) ?? true))
            {
                try
                {
                    errorMask?.PushIndex((int)Artist_FieldIndex.Albums);
                    KeyedDictXmlTranslation<String, Album>.Instance.Write(
                        node: elem,
                        name: nameof(item.Albums),
                        items: item.Albums.Values,
                        translationMask: translationMask,
                        errorMask: errorMask,
                        valTransl: (XElement subNode, Album subItem, ErrorMaskBuilder dictSubMask, TranslationCrystal dictTranslMask) =>
                        {
                            LoquiXmlTranslation<Album>.Instance.Write(
                                node: subNode,
                                item: subItem,
                                name: null,
                                errorMask: dictSubMask,
                                translationMask: dictTranslMask);
                        }
                        );
                }
                catch (Exception ex)
                when (errorMask != null)
                {
                    errorMask.ReportException(ex);
                }
                finally
                {
                    errorMask?.PopIndex();
                }
            }
        }
        #endregion

        #endregion

    }
    #endregion

    #region Modules
    #region Mask
    public class Artist_Mask<T> : IMask<T>, IEquatable<Artist_Mask<T>>
    {
        #region Ctors
        public Artist_Mask()
        {
        }

        public Artist_Mask(T initialValue)
        {
            this.Name = initialValue;
            this.Albums = new MaskItem<T, IEnumerable<MaskItem<T, Album_Mask<T>>>>(initialValue, null);
        }
        #endregion

        #region Members
        public T Name;
        public MaskItem<T, IEnumerable<MaskItem<T, Album_Mask<T>>>> Albums;
        #endregion

        #region Equals
        public override bool Equals(object obj)
        {
            if (!(obj is Artist_Mask<T> rhs)) return false;
            return Equals(rhs);
        }

        public bool Equals(Artist_Mask<T> rhs)
        {
            if (rhs == null) return false;
            if (!object.Equals(this.Name, rhs.Name)) return false;
            if (!object.Equals(this.Albums, rhs.Albums)) return false;
            return true;
        }
        public override int GetHashCode()
        {
            int ret = 0;
            ret = ret.CombineHashCode(this.Name?.GetHashCode());
            ret = ret.CombineHashCode(this.Albums?.GetHashCode());
            return ret;
        }

        #endregion

        #region All Equal
        public bool AllEqual(Func<T, bool> eval)
        {
            if (!eval(this.Name)) return false;
            if (this.Albums != null)
            {
                if (!eval(this.Albums.Overall)) return false;
                if (this.Albums.Specific != null)
                {
                    foreach (var item in this.Albums.Specific)
                    {
                        if (!eval(item.Overall)) return false;
                        if (!item.Specific?.AllEqual(eval) ?? false) return false;
                    }
                }
            }
            return true;
        }
        #endregion

        #region Translate
        public Artist_Mask<R> Translate<R>(Func<T, R> eval)
        {
            var ret = new Artist_Mask<R>();
            this.Translate_InternalFill(ret, eval);
            return ret;
        }

        protected void Translate_InternalFill<R>(Artist_Mask<R> obj, Func<T, R> eval)
        {
            obj.Name = eval(this.Name);
            if (Albums != null)
            {
                obj.Albums = new MaskItem<R, IEnumerable<MaskItem<R, Album_Mask<R>>>>();
                obj.Albums.Overall = eval(this.Albums.Overall);
                if (Albums.Specific != null)
                {
                    List<MaskItem<R, Album_Mask<R>>> l = new List<MaskItem<R, Album_Mask<R>>>();
                    obj.Albums.Specific = l;
                    foreach (var item in Albums.Specific)
                    {
                        MaskItem<R, Album_Mask<R>> mask = default(MaskItem<R, Album_Mask<R>>);
                        if (item != null)
                        {
                            mask = new MaskItem<R, Album_Mask<R>>();
                            mask.Overall = eval(item.Overall);
                            if (item.Specific != null)
                            {
                                mask.Specific = item.Specific.Translate(eval);
                            }
                        }
                        l.Add(mask);
                    }
                }
            }
        }
        #endregion

        #region Clear Enumerables
        public void ClearEnumerables()
        {
            this.Albums.Specific = null;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            return ToString(printMask: null);
        }

        public string ToString(Artist_Mask<bool> printMask = null)
        {
            var fg = new FileGeneration();
            ToString(fg, printMask);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg, Artist_Mask<bool> printMask = null)
        {
            fg.AppendLine($"{nameof(Artist_Mask<T>)} =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (printMask?.Name ?? true)
                {
                    fg.AppendLine($"Name => {Name}");
                }
                if (printMask?.Albums?.Overall ?? true)
                {
                    fg.AppendLine("Albums =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        if (Albums.Overall != null)
                        {
                            fg.AppendLine(Albums.Overall.ToString());
                        }
                        if (Albums.Specific != null)
                        {
                            foreach (var subItem in Albums.Specific)
                            {
                                fg.AppendLine("[");
                                using (new DepthWrapper(fg))
                                {
                                    fg.AppendLine($"Name => {subItem}");
                                }
                                fg.AppendLine("]");
                            }
                        }
                    }
                    fg.AppendLine("]");
                }
            }
            fg.AppendLine("]");
        }
        #endregion

    }

    public class Artist_ErrorMask : IErrorMask, IErrorMask<Artist_ErrorMask>
    {
        #region Members
        public Exception Overall { get; set; }
        private List<string> _warnings;
        public List<string> Warnings
        {
            get
            {
                if (_warnings == null)
                {
                    _warnings = new List<string>();
                }
                return _warnings;
            }
        }
        public Exception Name;
        public MaskItem<Exception, IEnumerable<MaskItem<Exception, Album_ErrorMask>>> Albums;
        #endregion

        #region IErrorMask
        public object GetNthMask(int index)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    return Name;
                case Artist_FieldIndex.Albums:
                    return Albums;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthException(int index, Exception ex)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    this.Name = ex;
                    break;
                case Artist_FieldIndex.Albums:
                    this.Albums = new MaskItem<Exception, IEnumerable<MaskItem<Exception, Album_ErrorMask>>>(ex, null);
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public void SetNthMask(int index, object obj)
        {
            Artist_FieldIndex enu = (Artist_FieldIndex)index;
            switch (enu)
            {
                case Artist_FieldIndex.Name:
                    this.Name = (Exception)obj;
                    break;
                case Artist_FieldIndex.Albums:
                    this.Albums = (MaskItem<Exception, IEnumerable<MaskItem<Exception, Album_ErrorMask>>>)obj;
                    break;
                default:
                    throw new ArgumentException($"Index is out of range: {index}");
            }
        }

        public bool IsInError()
        {
            if (Overall != null) return true;
            if (Name != null) return true;
            if (Albums != null) return true;
            return false;
        }
        #endregion

        #region To String
        public override string ToString()
        {
            var fg = new FileGeneration();
            ToString(fg);
            return fg.ToString();
        }

        public void ToString(FileGeneration fg)
        {
            fg.AppendLine("Artist_ErrorMask =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (this.Overall != null)
                {
                    fg.AppendLine("Overall =>");
                    fg.AppendLine("[");
                    using (new DepthWrapper(fg))
                    {
                        fg.AppendLine($"{this.Overall}");
                    }
                    fg.AppendLine("]");
                }
                ToString_FillInternal(fg);
            }
            fg.AppendLine("]");
        }
        protected void ToString_FillInternal(FileGeneration fg)
        {
            fg.AppendLine($"Name => {Name}");
            fg.AppendLine("Albums =>");
            fg.AppendLine("[");
            using (new DepthWrapper(fg))
            {
                if (Albums.Overall != null)
                {
                    fg.AppendLine(Albums.Overall.ToString());
                }
                if (Albums.Specific != null)
                {
                    foreach (var subItem in Albums.Specific)
                    {
                        fg.AppendLine("[");
                        using (new DepthWrapper(fg))
                        {
                            fg.AppendLine($"Name => {subItem}");
                        }
                        fg.AppendLine("]");
                    }
                }
            }
            fg.AppendLine("]");
        }
        #endregion

        #region Combine
        public Artist_ErrorMask Combine(Artist_ErrorMask rhs)
        {
            var ret = new Artist_ErrorMask();
            ret.Name = this.Name.Combine(rhs.Name);
            ret.Albums = new MaskItem<Exception, IEnumerable<MaskItem<Exception, Album_ErrorMask>>>(this.Albums.Overall.Combine(rhs.Albums.Overall), new List<MaskItem<Exception, Album_ErrorMask>>(this.Albums.Specific.And(rhs.Albums.Specific)));
            return ret;
        }
        public static Artist_ErrorMask Combine(Artist_ErrorMask lhs, Artist_ErrorMask rhs)
        {
            if (lhs != null && rhs != null) return lhs.Combine(rhs);
            return lhs ?? rhs;
        }
        #endregion

        #region Factory
        public static Artist_ErrorMask Factory(ErrorMaskBuilder errorMask)
        {
            if (errorMask?.Empty ?? true) return null;
            return new Artist_ErrorMask();
        }
        #endregion

    }
    public class Artist_CopyMask
    {
        #region Members
        public bool Name;
        public MaskItem<CopyOption, Album_CopyMask> Albums;
        #endregion

    }
    public class Artist_TranslationMask : ITranslationMask
    {
        #region Members
        private TranslationCrystal _crystal;
        public bool Name;
        public MaskItem<bool, Album_TranslationMask> Albums;
        #endregion

        #region Ctors
        public Artist_TranslationMask()
        {
        }

        public Artist_TranslationMask(bool defaultOn)
        {
            this.Name = defaultOn;
            this.Albums = new MaskItem<bool, Album_TranslationMask>(defaultOn, null);
        }

        #endregion

        public TranslationCrystal GetCrystal()
        {
            if (_crystal != null) return _crystal;
            List<(bool On, TranslationCrystal SubCrystal)> ret = new List<(bool On, TranslationCrystal SubCrystal)>();
            GetCrystal(ret);
            _crystal = new TranslationCrystal()
            {
                Crystal = ret.ToArray()
            };
            return _crystal;
        }

        protected void GetCrystal(List<(bool On, TranslationCrystal SubCrystal)> ret)
        {
            ret.Add((Name, null));
            ret.Add((Albums?.Overall ?? true, Albums?.Specific?.GetCrystal()));
        }
    }
    #endregion

    #endregion

}
